name: panelQuiz
version: '1.0-SNAPSHOT'
main: ramune314159265.panelQuiz.PanelQuiz
api-version: '1.20'
authors: [ ramune314159265 ]
description: Minecraft PanelQuiz
commands:
  startQuiz:
    description: Start a new quiz
    permission: panelQuiz.command.startquiz
    usage: /startquiz <quizType> <question> <quizColumn>
  answerQuestion:
    description: Answer the question
    aliases: [ aq ]
    usage: /answerquestion <index>

permissions:
  panelQuiz.command.*:
    description: Allows you to perform commands in this plugin.
    children:
      wsconnectionplugin.command.startquiz: true
  panelQuiz.command.startquiz:
    description: Allows you to perform /startquiz command.
    default: op