name: panelQuiz
version: '1.0-SNAPSHOT'
main: ramune314159265.panelQuiz.PanelQuiz
api-version: '1.20'
authors: [ ramune314159265 ]
description: Minecraft PanelQuiz
commands:
  startQuiz:
    description: Start a new quiz
    permission: panelQuiz.command.startquiz
    usage: /startquiz <quizType> <question> <quizColumn>
  answerQuestion:
    description: Answer the question
    aliases: [ aq ]
    usage: /answerquestion <index>
  lockQuiz:
    description: Lock the question
    permission: panelQuiz.command.lockquiz
    usage: /lockquestion
  showQuizInfo:
    description: Show the question info
    permission: panelQuiz.command.showquizinfo
    usage: /showquizinfo

permissions:
  panelQuiz.command.*:
    description: Allows you to perform commands in this plugin.
    children:
      wsconnectionplugin.command.startquiz: true
      wsconnectionplugin.command.lockquiz: true
      wsconnectionplugin.command.showquizinfo: true
  panelQuiz.command.startquiz:
    description: Allows you to perform /startquiz command.
    default: op
  panelQuiz.command.lockquiz:
    description: Allows you to perform /lockquiz command.
    default: op
  panelQuiz.command.showquizinfo:
    description: Allows you to perform /showquizinfo command.
    default: op