name: panelQuiz
version: '1.2'
main: ramune314159265.panelQuiz.PanelQuiz
api-version: '1.20'
authors: [ ramune314159265 ]
description: Minecraft PanelQuiz
commands:
  panelQuiz:
    description: A command for managing this plugin
    permission: panelQuiz.command.panelquiz
    usage: /panelquiz <subCommand>
  answerQuestion:
    description: Answer the question
    aliases: [ aq ]
    usage: /answerquestion <index>

permissions:
  panelQuiz.command.*:
    description: Allows you to perform commands in this plugin.
    children:
      wsconnectionplugin.command.panelquiz: true
  panelQuiz.command.panelquiz:
    description: Allows you to perform /panelquiz command.
    default: op