name: panelQuiz
version: '1.0-SNAPSHOT'
main: ramune314159265.panelQuiz.PanelQuiz
api-version: '1.20'
authors: [ ramune314159265 ]
description: Minecraft PanelQuiz
commands:
  panelQuiz:
    description: A command for managing this plugin
    permission: panelQuiz.command.panelquiz
    usage: /panelquiz <subCommand>
  startQuiz:
    description: Start a new quiz
    permission: panelQuiz.command.startquiz
    usage: /startquiz <quizType> <question> <quizColumn>
  answerQuestion:
    description: Answer the question
    aliases: [ aq ]
    usage: /answerquestion <index>
  lockQuiz:
    description: Lock the question
    permission: panelQuiz.command.lockquiz
    usage: /lockquestion
  showQuizInfo:
    description: Show the question info
    permission: panelQuiz.command.showquizinfo
    usage: /showquizinfo
  judgeAnswer:
    description: Judge the answers
    permission: panelQuiz.command.judgeanswer
    usage: /judgeanswer [<index>] [<true|false>]
  announceQuiz:
    description: Announce the quiz
    permission: panelQuiz.command.announcequiz
    usage: /announcequiz <preTitle>
  cancelQuiz:
    description: Cancel the quiz
    permission: panelQuiz.command.cancelquiz
    usage: /cancelquiz
  reloadPanelQuizPlugin:
    description: Reload the plugin
    permission: panelQuiz.command.reload
    usage: /reloadpanelquizplugin
  openAnswers:
    description: Open the answers
    permission: panelQuiz.command.openanswers
    usage: /openanswers

permissions:
  panelQuiz.command.*:
    description: Allows you to perform commands in this plugin.
    children:
      wsconnectionplugin.command.panelquiz: true
      wsconnectionplugin.command.startquiz: true
      wsconnectionplugin.command.lockquiz: true
      wsconnectionplugin.command.showquizinfo: true
      wsconnectionplugin.command.judgeanswer: true
      wsconnectionplugin.command.announcequiz: true
      wsconnectionplugin.command.cancelquiz: true
      wsconnectionplugin.command.reload: true
      wsconnectionplugin.command.openanswers: true
  panelQuiz.command.panelquiz:
    description: Allows you to perform /panelquiz command.
    default: op
  panelQuiz.command.startquiz:
    description: Allows you to perform /startquiz command.
    default: op
  panelQuiz.command.lockquiz:
    description: Allows you to perform /lockquiz command.
    default: op
  panelQuiz.command.showquizinfo:
    description: Allows you to perform /showquizinfo command.
    default: op
  panelQuiz.command.judgeanswer:
    description: Allows you to perform /judgeanswer command.
    default: op
  panelQuiz.command.announcequiz:
    description: Allows you to perform /announcequiz command.
    default: op
  panelQuiz.command.cancelquiz:
    description: Allows you to perform /cancelquiz command.
    default: op
  panelQuiz.command.reload:
    description: Allows you to perform /reloadpanelquizplugin command.
    default: op
  panelQuiz.command.openanswers:
    description: Allows you to perform /openanswers command.
    default: op